version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - npm install

  build:
    commands:
      - npm run build

artifacts:
  files:
    - '**/*'
    - buildspec.yml         # Include buildspec.yml at root
    - appspec.yml           # Include appspec.yml at root
    - scripts/**            # Include all scripts inside scripts/
  base-directory: build
